version: '3.7'

services:
  github-actions-runner:
    build:
      context: .
      args:
        GITHUB_REPO: https://github.com/efcs/compiler-images
        GITHUB_TOKEN: ${GITHUB_REGISTRATION_TOKEN:?required}
    image: github-actions-runner
