version: '3.7'

x-build-clang: &build-clang
    context: ..
    dockerfile: compilers/clang.Dockerfile

x-build-gcc: &build-gcc
    context: ..
    dockerfile: compilers/gcc.Dockerfile

services:
  gcc-4.8.5:
    build:
      <<: *build-gcc
      args:
        branch: releases/gcc-4.8.5
        cherry_pick: 3a27b4db566c2cde8e043220f3d2c5401159b10e
    image: efcs/compiler-images/gcc-4.8.5:final
  gcc-4.9.4:
    build:
      <<: *build-gcc
      args:
        branch: releases/gcc-4.9.4
    image: efcs/compiler-images/gcc-4.9.4:final
  gcc-5:
    build:
      <<: *build-gcc
      args:
        branch: releases/gcc-5.5.0
    image: efcs/compiler-images/gcc-5:final
  gcc-6:
    build:
      <<: *build-gcc
      args:
        branch: releases/gcc-6.5.0
    image: efcs/compiler-images/gcc-6:final
  gcc-7:
    build:
      <<: *build-gcc
      args:
        branch: releases/gcc-7.4.0
    image: efcs/compiler-images/gcc-7:final
  gcc-8:
    build:
      <<: *build-gcc
      args:
        branch: releases/gcc-8.2.0
    image: efcs/compiler-images/gcc-8:final
  gcc-9:
    build:
      <<: *build-gcc
      args:
        branch: releases/gcc-9.2.0
    image: efcs/compiler-images/gcc-9:final
  # Add LLVM compilers
  llvm-3.6:
    build:
      <<: *build-clang
      args:
        branch: release/3.6.x
        CC: gcc
        CXX: g++
    image: efcs/compiler-images/llvm-3.6:final
  llvm-3.7:
    build:
      <<: *build-clang
      args:
        branch: release/3.7.x
        CC: gcc
        CXX: g++
    image: efcs/compiler-images/llvm-3.7:final
  llvm-3.8:
    build:
      <<: *build-clang
      args:
        branch: release/3.8.x
        CC: gcc
        CXX: g++
    image: efcs/compiler-images/llvm-3.8:final
  llvm-3.9:
    build:
      <<: *build-clang
      args:
        branch: release/3.9.x
        CC: gcc
        CXX: g++
    image: efcs/compiler-images/llvm-3.9:final
  llvm-4:
    build:
      <<: *build-clang
      args:
        branch: release/4.x
        CC: gcc
        CXX: g++
    image: efcs/compiler-images/llvm-4:final
  llvm-5:
    build:
      <<: *build-clang
      args:
        branch: release/5.x
    image: efcs/compiler-images/llvm-5:final
  llvm-6:
    build:
      <<: *build-clang
      args:
        branch: release/6.x
    image: efcs/compiler-images/llvm-6:final
  llvm-7:
    build:
      <<: *build-clang
      args:
        branch: release/7.x
    image: efcs/compiler-images/llvm-7:final
  llvm-8:
    build:
      <<: *build-clang
      args:
        branch: release/8.x
    image: efcs/compiler-images/llvm-8:final
  llvm-9:
    build:
      <<: *build-clang
      args:
        branch: release/9.x
    image: efcs/compiler-images/llvm-9:final
  gcc-tot:
    build:
      <<: *build-gcc
      args:
        branch: master
        cache_date: ${TODAYS_DATE:?export TODAYS_DATE=$(date +'%F')}
    image: efcs/compiler-images/gcc-tot:undated
  llvm-tot:
    build:
      <<: *build-clang
      args:
        branch: master
        cache_date: ${TODAYS_DATE:?export TODAYS_DATE=$(date +'%F')}
    image: efcs/compiler-images/llvm-tot:undated
