name: Publish Docker image to GitHub Package Registry
on:
  push:
    branches:
      - master
    paths: images/gcc-4.8.5/**
jobs:
  build:
    runs-on: [self-hosted]
    steps:
    - name: Copy Repo Files
      uses: actions/checkout@master
    - name: Publish Docker Image to GPR
      uses: ericwf/gpr-docker-publish@master
      id: docker
      with:
        IMAGE_NAME: 'gcc-4.8.5'
        TAG: 'final'
        DOCKERFILE_PATH: 'images/gcc-4.8.5/Dockerfile'
        BUILD_CONTEXT: '.'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
