name: Publish Docker image to GitHub Package Registry
on:
  push:
    branches:
      - master
    paths:
      images/test-image/**

jobs:
  build:
    runs-on: [ubuntu-latest]
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: build-push
      uses: docker/build-push-action@v1
      with:
        registry: docker.pkg.github.com
        username: publisher
        password: ${{ secrets.GITHUB_TOKEN }}
        repository: efcs/compiler-images/test-image
        tags: latest
        path: images/test-image


