name: Publish Docker image to GitHub Package Registry
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: [ubuntu-latest]
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: build
      id: build
      uses: docker/build-action@v1
      with:
        repository: efcs/compiler-images/test-image
        tags: latest
        path: images/test-image
    - name: login
      uses: docker/login-action@v1
      with:
        registry: docker.pkg.github.com
        username: publisher
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: push
      uses: docker/push-action@v1
      with:
        registry: docker.pkg.github.com
        tags: ${{ outputs.build.tags }}
